# Generated by Django 5.1.3 on 2024-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0002_imagem_alter_produto_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
